config/routes.rb
PayMe::Application.routes.draw do

  root :to => 'payments#new'  
  match '/thanks' => 'payments#thanks', :as => :thanks
  get '/admin' => 'payments#index'
  
  resources :payments
  
  get '*asdf' => 'static#_404'
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper
  
  after_save :send_sms
  
  attr_accessor :stripe_card_token
  
  def save_with_payment
      if valid?
        charge = Stripe::Charge.create(amount: (amount*100).to_i, currency: "usd", card: stripe_card_token, description: "#{name}, #{email}")
        save!
      end
    rescue Stripe::InvalidRequestError => e
      logger.error "Stripe error while charging customer: #{e.message}"
      errors.add :base, "There was a problem with your credit card. Your credit card should not have been charged."
      false
  end
  
  def send_sms 

    TWILIO.account.sms.messages.create(
      :from => NUMBER_REGISTERED_WITH_TWILIO,
      :to => NUMBER_TO_RECEIVE_NOTIFICATIONS_ON,
      :body => "#{name} just paid you #{number_to_currency(amount)} Say thanks! #{email}"
    )
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_filter :auth, :except => [:new, :create, :thanks]
  
  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payments }
    end
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
    @payment = Payment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/new
  # GET /payments/new.json
  def new
    @payment = Payment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/1/edit
  def edit
    @payment = Payment.find(params[:id])
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(params[:payment])
    if @payment.save_with_payment
      session[:payment_id] = @payment.id
      redirect_to :action => 'thanks'
    else
      render :new, :error => "Sorry #{params[:payment][:name]}, your card was unable to be processed. Please check to make sure everything is entered correctly!"
    end
  end
  
  def thanks
    if session[:payment_id].present?
      @payment = Payment.find(session[:payment_id])
      session[:payment_id] = nil
    else
      redirect_to root_path
    end
    
  end

  # PUT /payments/1
  # PUT /payments/1.json
  def update
    @payment = Payment.find(params[:id])

    respond_to do |format|
      if @payment.update_attributes(params[:payment])
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment = Payment.find(params[:id])
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end
  
  private
  
  def auth
    authenticate_or_request_with_http_digest(REALM) do |username|
      USERS_TABLE[username]
    end
  end
  
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  
  def _404
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
  <title>Pay <%= YOUR_NAME %></title>
	<link REL="SHORTCUT ICON" HREF="http://src.sencha.io/16/16/http://graph.facebook.com/FriendJonathanLeung/picture">
	<%= tag :meta, :name => "stripe_public_key", :content => STRIPE_PUBLIC_KEY %>
	<%= tag :meta, :name => "person_name", :content => YOUR_NAME %>
	<%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/payments/_form.html.erb
<div id="payment-errors" style="width:200px"><br></div>

<%= form_for(@payment, :html => { :id => "payment-form" }) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<%= f.hidden_field :stripe_card_token %>
		
  <div class="field">
    <%= f.label :name, "Your Full Name" %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <!-- <%= f.label :description %>
    <%= f.text_area :description, :cols => 20, :rows => 2 %> -->
  </div>

	<br>
	<h3>Credit Card Information</h3>
	<br>
  <div class="field">
		<%= label_tag :amount, "Transaction Amount" %>
		<div class="input-prepend">
			<span class="add-on">$</span>
			<%= f.text_field :amount, :class => "span1" %>
		</div>
    <%= label_tag :card_number, "Credit Card Number", :class=>"form-row" %>
    <%= text_field_tag :card_number, nil, name: nil, :class => "span2" %>
  </div>
  <div class="field">
    <%= label_tag :card_code, "Card Security Code (CVC)" %>
    <%= text_field_tag :card_code, nil, name: nil, :class => "span1" %>
  </div>
  <div class="field">
    <%= label_tag :card_month, "Card Expiration" %>
    <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month", class: "span2"} %>
    <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year", class: "span1"} %>
  </div>


	<div id="stripe_error">
	  <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
	</div>

  <div class="actions">
    <%= f.submit "Submit Payment", :class => "btn btn-large btn-primary", :id => "submit-button" %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<div class="container-fluid">
<div class="well span8">

<h1>Payments Index</h1>
<br>
<table class="table table-bordered">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sum = 0 %>

<% @payments.each do |payment| %>
	<% @sum += payment.amount %>
  <tr>
    <td><%= payment.name %></td>
    <td><%= payment.email %></td>
    <td><%= number_to_currency payment.amount %></td>
    <td><%= link_to 'Show', payment %></td>
    <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
    <td><%= link_to 'Destroy', payment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
	<tr>
		<td></td>
		<td style="text-align:right;"><strong>Total</strong></td>
		<td><strong><%= number_to_currency(@sum) %></strong></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
</table>


</div> <!-- /well -->
</div> <!-- /container -->

app/views/payments/new.html.erb
<div class="container-fluid">
<div class="well span4">

<h1 style="font-size:25px">Pay <%= YOUR_NAME %></h1><br>

<%= render 'form' %>

</div> <!-- /well -->
</div> <!-- /container -->

app/views/payments/show.html.erb
<div class="container-fluid">
<div class="well span4">

<h1 style="font-size:25px">Thanks <%= @payment.name %>!</h1><br>
	<p id="notice"><%= notice %></p>
	<p>
	  <b>Name:</b>
	  <%= @payment.name %>
	</p>

	<p>
	  <b>Email:</b>
	  <%= @payment.email %>
	</p>

	<p>
	  <b>Amount:</b>
	  <%= number_to_currency @payment.amount %>
	</p>
	<br>
	<%= link_to 'Back', payments_path, :class => "btn" %>
	

</div> <!-- /well -->
</div> <!-- /container -->

app/views/payments/thanks.html.erb
<div class="container-fluid">
<div class="well span5">

<h1 style="font-size:25px">Thanks <%= @payment.name %>!</h1><br>
	<p id="notice"><%= notice %></p>
	<p>I have received your
		<strong>
			<%= number_to_currency(@payment.amount) %>
		</strong>
		transaction!
	</p>
	<p>Thanks!</p>
	<br>
	<%= link_to 'Go Back', root_path, :class => "btn" %>
</div> <!-- /well -->
</div> <!-- /container -->